name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "dzmiter.auchynnikau@gmail.com"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}